### ISSUE TITLE
issue installing gatekeeper

### ISSUE THREAD

**Issue by andreaguarise** [icclab/cyclops-dashboard#2]
Hi, 

I'm evaluating your software within the technology scouting phase for the billing aspects of a research project on cloud computing of the Italian Institute for Nuclear Physics (INFN). Your software seems to be interesting and promising, and in the last couple of day I tried to hav it working on a testbed. Unfortunetely since yesterday I'm nont abel to install the dashboard. 

While installing the gatekeeper I receive this error trace:

getting all code dependencies for auth-utils now, be patient ~ 1-2 minutes
./install.sh: line 68: 25759 Segmentation fault      (core dumped) go get
done.
compiling and installing the package
auth-utils.go:26:2: cannot find package "code.google.com/p/gcfg" in any of:
    /usr/src/pkg/code.google.com/p/gcfg (from $GOROOT)
    /home/ubuntu/go/src/code.google.com/p/gcfg (from $GOPATH)
auth-utils.go:28:2: cannot find package "github.com/gorilla/mux" in any of:
    /usr/src/pkg/github.com/gorilla/mux (from $GOROOT)
    /home/ubuntu/go/src/github.com/gorilla/mux (from $GOPATH)
auth.go:32:2: cannot find package "github.com/mattn/go-sqlite3" in any of:
    /usr/src/pkg/github.com/mattn/go-sqlite3 (from $GOROOT)
    /home/ubuntu/go/src/github.com/mattn/go-sqlite3 (from $GOPATH)
done.
starting the auth-service next, you can start using it at port :8000
use Ctrl+c to stop it. The executable is located at: /home/ubuntu/go/bin/auth-utils
./install.sh: line 80: auth-utils: command not found

Can you please help me fix this?

The OS is:
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty

Tank in advance!

Cheers,
Andrea Guarise

**Comment by piyush82** [comment]
Hi Andrea,

Sometimes (although rarely) go get command which basically fetches the
dependent libraries from remote repositories fails because the repos don't
respond in time or if you don't have internet connectivity.

Can you kindly simply try the 'go get' command again manually and see if it
fixes the issue?

Kind regards,
Piyush

---

Dr. Piyush Harsh, Ph.D.
Researcher, InIT Cloud Computing Lab
Zurich University of Applied Sciences (ZHAW)
[Site] http://piyush-harsh.info
[Google-Scholar] https://scholar.google.ch/citations?hl=en&user=kaSUIp8AAAAJ

[Research Lab] blog.zhaw.ch/icclab
Fax: +41(0)58.935.7403 GPG Keyid: 9C5A8838

**Comment by piyush82** [comment]
Dear Andrea,

I was able to replicate your problem. The issue was the gcfg module was no
longer available from google code repositories. I have changed the location
to github repository for gcfg and it seems to be working now.

You can redeploy gatekeeper and hopefully it should work.

Kind regards,
Piyush

---

Dr. Piyush Harsh, Ph.D.
Researcher, InIT Cloud Computing Lab
Zurich University of Applied Sciences (ZHAW)
[Site] http://piyush-harsh.info
[Google-Scholar] https://scholar.google.ch/citations?hl=en&user=kaSUIp8AAAAJ

[Research Lab] blog.zhaw.ch/icclab
Fax: +41(0)58.935.7403 GPG Keyid: 9C5A8838

**Comment by andreaguarise** [comment]
HI Piyush,

Thanks for the fast answer. I just checked out the code from scratch and the original issue is fixed. Unfortunately now the build stops with another error:

getting all code dependencies for auth-utils now, be patient ~ 1-2 minutes
  github.com/mattn/go-sqlite3
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
done.
compiling and installing the package 
 github.com/mattn/go-sqlite3
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
Go type not supported in export: [0]byte
done.
starting the auth-service next, you can start using it at port :8000
use Ctrl+c to stop it. The executable is located at: /home/ubuntu/go/bin/auth-utils
install.sh: line 80: auth-utils: command not found

Cheers,
Andrea

**Comment by piyush82** [comment]
Dear Andrea,

Looks like you are having trouble cloning these git repos. You can do this
manually also.

Under the go/src/github.com/ folder simply clone mattn/go-sqlite3 code repo
and also for other dependencies whose git clone fails.

Make sure that you create the author's folder first inside the src folder.

So after cloning manuall, the folder path should look like: go/src/
github.com/mattn/go-sqlite3/

Let me know how it goes.

BR,
Piyush

---

Dr. Piyush Harsh, Ph.D.
Researcher, InIT Cloud Computing Lab
Zurich University of Applied Sciences (ZHAW)
[Site] http://piyush-harsh.info
[Google-Scholar] https://scholar.google.ch/citations?hl=en&user=kaSUIp8AAAAJ

[Research Lab] blog.zhaw.ch/icclab
Fax: +41(0)58.935.7403 GPG Keyid: 9C5A8838

**Comment by piyush82** [comment]
Also if you are doing things manually, do not forget to 'source
$HOME/.profile' before attempting "go get" and "go install" commands.

Piyush

---

Dr. Piyush Harsh, Ph.D.
Researcher, InIT Cloud Computing Lab
Zurich University of Applied Sciences (ZHAW)
[Site] http://piyush-harsh.info
[Google-Scholar] https://scholar.google.ch/citations?hl=en&user=kaSUIp8AAAAJ

[Research Lab] blog.zhaw.ch/icclab
Fax: +41(0)58.935.7403 GPG Keyid: 9C5A8838

**Comment by andreaguarise** [comment]
Ok, I've figured out what this issue was: 

The dependencies where correctly cloned, but I had gccgo-go package installed on the machine, and this (probably with an older version of go) was masking the 1.4.2 go version needed by one of the dependencies. Now gatekeeper correctly builds and starts.

I think you can close the issue.

Thank you very much!

Andrea

**Comment by piyush82** [comment]
Issue resolved!
