### ISSUE TITLE
ch.icclab.cyclops.dashboard.applicationFactory.McnDashboardApplicationFactory

### ISSUE THREAD

**Issue by rwoznica** [icclab/cyclops-dashboard#3]
Dear all,

I am getting

Error while getting the Application Class loaded: ch.icclab.cyclops.dashboard.applicationFactory.McnDashboardApplicationFactory

in 
/var/log/cyclops/dashboard.log.

All steps seems to be done, no  visible signs of error (other than that one). Any idea?

Thank you

**Comment by piyush82** [comment]
Looks like the environment variable for Cyclops is not properly set, can
you include the configuration files (all services) so that we can analyze
the issue more properly?

Cyclops Dev-Team

---

Dr. Piyush Harsh, Ph.D.
Researcher, InIT Cloud Computing Lab
Zurich University of Applied Sciences (ZHAW)
[Site] http://piyush-harsh.info
[Google-Scholar] https://scholar.google.ch/citations?hl=en&user=kaSUIp8AAAAJ

[Research Lab] blog.zhaw.ch/icclab
Fax: +41(0)58.935.7403 GPG Keyid: 9C5A8838

**Comment by rwoznica** [comment]
Sure, here they are. Single machine (local) deployement.

There used to be section like this in Dashboard configuration file (now changed to „Environment=“)

######################## ADVANCED SETTINGS ######################

# Environment variable

Environment=Mcn

Best regards

Radim Woznica

**Comment by ManuPerezBelmonte** [comment]
Hello rwoznica, 

We have been checking our code and upgrading it to solve the issues and have better performance, The issue that we had here was regarding the packaging structure, which is solved now in our new release for [UDR](https://github.com/icclab/cyclops-udr/tree/eca4351244e535ddd0d17df0462fa5d838876bde), [RC](https://github.com/icclab/cyclops-rc/tree/b8a6c4d005115b0d371cda20260098695aa79f45) and [Dashboard](https://github.com/icclab/cyclops-dashboard/tree/13e98fc426b8cff6bdd105687ed78ef2bd5cb3e4) micro services. 
You shouldn't have any problem right now to deploy and use it. Please let us know if your issue was solved.

Thanks, 
Cyclops Team.

**Comment by rwoznica** [comment]
Thank you. I am going to check this soon.

Best regards, RW

**Comment by rwoznica** [comment]
Hello, current release does not seem to be consistent. Please advise on usage of Environment=Mcn variable. Any documentation on how to handle such a type of setting. I suppose this does have to do something with tenant setup, however any docs are missing. Thank you

**Comment by piyush82** [comment]
Hi,

I have asked my colleague to update the README to include more clarity on
this field. Short answer is: generally you should not use Mcn option as it
is to support one of the use cases from European Framework project titled
MCN.

Kind regards,
Piyush

---

Dr. Piyush Harsh, Ph.D.
Researcher, InIT Cloud Computing Lab
Zurich University of Applied Sciences (ZHAW)
[Site] http://piyush-harsh.info
[Google-Scholar] https://scholar.google.ch/citations?hl=en&user=kaSUIp8AAAAJ

[Research Lab] blog.zhaw.ch/icclab
Fax: +41(0)58.935.7403 GPG Keyid: 9C5A8838
